# Generated by Django 5.0.1 on 2024-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('site_header', models.CharField(max_length=90)),
                ('header_background', models.ImageField(upload_to='image')),
                ('feature_1', models.CharField(max_length=50)),
                ('feature_text_1', models.CharField(max_length=50)),
                ('feature_2', models.CharField(max_length=50)),
                ('feature_text_2', models.CharField(max_length=50)),
                ('feature_3', models.CharField(max_length=50)),
                ('feature_text_3', models.CharField(max_length=50)),
                ('feature_4', models.CharField(max_length=50)),
                ('feature_text_4', models.CharField(max_length=50)),
                ('shop_heading', models.CharField(max_length=50)),
                ('second_feauture_1', models.CharField(max_length=30)),
                ('second_feauture_1_image', models.ImageField(upload_to='image')),
                ('second_feature_1_text', models.CharField(max_length=40)),
                ('second_feauture_2', models.CharField(max_length=30)),
                ('second_feauture_2_image', models.ImageField(upload_to='image')),
                ('second_feature_2_text', models.CharField(max_length=40)),
                ('second_feauture_3', models.CharField(max_length=30)),
                ('second_feauture_3_image', models.ImageField(upload_to='image')),
                ('second_feature_3_text', models.CharField(max_length=40)),
                ('section_shop_heading', models.CharField(max_length=30)),
                ('banner_header', models.CharField(max_length=40)),
                ('banner_header_completion', models.CharField(max_length=40)),
                ('banner_text', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(upload_to='image')),
                ('banner_price', models.CharField(max_length=10)),
                ('banner_quantity', models.IntegerField()),
                ('best_seller_title', models.CharField(max_length=50)),
                ('best_seller_text', models.CharField(max_length=200)),
                ('satisfied_customers', models.IntegerField()),
                ('quality_of_service', models.IntegerField()),
                ('quality_certificates', models.IntegerField()),
                ('available_products', models.IntegerField()),
                ('footer_text', models.CharField(max_length=30)),
                ('copyright_text', models.CharField(max_length=30)),
            ],
        ),
    ]
