# Generated by Django 5.0.1 on 2024-09-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index_page',
            old_name='second_feauture_1',
            new_name='second_feature_1',
        ),
        migrations.RenameField(
            model_name='index_page',
            old_name='second_feauture_1_image',
            new_name='second_feature_1_image',
        ),
        migrations.RenameField(
            model_name='index_page',
            old_name='second_feauture_2',
            new_name='second_feature_2',
        ),
        migrations.RenameField(
            model_name='index_page',
            old_name='second_feauture_2_image',
            new_name='second_feature_2_image',
        ),
        migrations.RenameField(
            model_name='index_page',
            old_name='second_feauture_3',
            new_name='second_feature_3',
        ),
        migrations.RenameField(
            model_name='index_page',
            old_name='second_feauture_3_image',
            new_name='second_feature_3_image',
        ),
    ]
