# Generated by Django 5.0.1 on 2024-09-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RenameModel(
            old_name='Slider',
            new_name='First_slider',
        ),
    ]
