# Generated by Django 5.0.1 on 2024-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_first_slider_options_alter_index_page_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'Sign_up_image',
                'verbose_name_plural': 'sign_up_image',
            },
        ),
    ]
