# Generated by Django 5.0.1 on 2024-09-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='send_to_home_page',
        ),
    ]
