# Generated by Django 5.0.1 on 2024-09-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_products_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
