# Generated by Django 5.0.1 on 2024-09-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=30),
        ),
    ]
