# Generated by Django 5.0.1 on 2024-09-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='number_of_post',
            field=models.IntegerField(null=True),
        ),
    ]
