# Generated by Django 5.0.1 on 2024-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_category_number_of_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
