# Generated by Django 5.0.1 on 2024-09-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='comment_image',
        ),
    ]
