# Generated by Django 5.0.1 on 2024-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_featured_price_featured_products_featured_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('order_notes', models.TextField(max_length=500)),
                ('local_pickup', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=6)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('total_order_price', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
