# Generated by Django 5.0.1 on 2024-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_billing_details_ordered_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordered_products',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
    ]
