# Generated by Django 5.0.1 on 2024-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_billing_details_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing_details',
            options={'verbose_name': 'Billing_detail', 'verbose_name_plural': 'Billing_details'},
        ),
        migrations.AlterModelOptions(
            name='ordered_products',
            options={'verbose_name': 'Ordered_products', 'verbose_name_plural': 'Ordered_products'},
        ),
        migrations.AddField(
            model_name='billing_details',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='total_order_price',
            field=models.IntegerField(null=True),
        ),
    ]
