# Generated by Django 5.0.1 on 2024-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_billing_details_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='total_order_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordered_products',
            name='total_order_price',
            field=models.FloatField(),
        ),
    ]
