# Generated by Django 5.0.1 on 2024-10-07 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_billing_details_total_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_products',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
